---
framework: mocha
preRun:
     command:
        - npm install
preMerge:
  pattern:
    - test/unit/**/*.js
postMerge:
  pattern: 
    - test/unit/**/*.js
postRun:
     command:
        - node --version
configFile: mocharc.yml
version: 1.0.0

